name: IaC ECS - Local Validation Checks

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**' 

env:
  TF_VAR_aws_region: eu-west-1

jobs:
  terraform_local_checks:
    name: 'Terraform Local Checks'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.x 

      - name: Install TFLint
        run: |
          TFLINT_VERSION=$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep "tag_name" | cut -d : -f 2 | tr -d " \",v")
          echo "Installing TFLint version $TFLINT_VERSION"
          curl -sL "https://github.com/terraform-linters/tflint/releases/download/v${TFLINT_VERSION}/tflint_linux_amd64.zip" -o tflint.zip
          unzip tflint.zip
          sudo mv tflint /usr/local/bin/tflint
          tflint --version
        shell: bash

      - name: Terraform Init (Local Backend)
        id: init
        run: |
          terraform init
        shell: bash

      - name: Terraform Format Check
        run: |
          terraform fmt --check
        shell: bash

      - name: Terraform Validate
        run: |
          terraform validate
        shell: bash

      - name: Run TFLint
        run: |
          tflint --recursive
        shell: bash
        continue-on-error: true 
